### ISSUE TITLE
How to make an input file to test the code?

### ISSUE THREAD

**Issue by Zenilos** [chrhansk/time-dependent-tsp#1]
Hello,
How to make an input file of a graph for this code?

**Comment by chrhansk** [comment]
Hey, we generate our test instances [here](https://github.com/chrhansk/time-dependent-tsp/blob/main/src/main/instance.cc): We basically distribute points in a plane to get the static instance and then augment the travel times to be time-dependent.

We do not persist the instances as files. Therefore, there are no input files (and no format). If you have instances which you want to solve, we can extend the code. Do you want to use the code to solve other instances?

**Comment by Zenilos** [comment]
Hi,
I want to use it on OSM graph. So if there is a way of making input file and feed it to the code I  can write a wrapper for that.
For example something like  this:
<img src="https://user-images.githubusercontent.com/47074370/127989560-df853d2d-d300-4e95-9523-b495606285b7.png">
converts to a file like this for 24 hours. ( each hour a weight):
<img src="https://user-images.githubusercontent.com/47074370/127994223-e2aa3ea7-ee32-4ce2-86a8-ee7d2060053c.png" >

**Comment by chrhansk** [comment]
Just to make sure: You always round travel times to integers, correct? (In your example the arc 2->3)?

I am rather busy this week, but I could implement a simple reader based on CSV for your use case next week...

**Comment by Zenilos** [comment]
Very good.
let's assume this is the csv file schema.
```
link_id,from_node_id,to_node_id,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
123,1, 2,20,1,2,3,4,35,6,37,8,9,140,11,12,13,14,15,516,17,18,19,20,21,22,23
123_r,2,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,315,167,17,518,139,204,21,22,23
```
For each hour we have a weight(0,1,2,...,22,23) for our graph. weights are integer.
node ids are integer, link_ids are character.

**Comment by Zenilos** [comment]
I made a sample weighted graph here:
https://gist.github.com/MINIMALaq/461bffdc6ecf6f9593ebb87e8235b49c

**Comment by chrhansk** [comment]
That seems reasonable, let me see what I can do :)

**Comment by chrhansk** [comment]
By the way, I just noticed that you sample is somewhat incomplete, since it has no tour to begin with. We generally formulate TSP variants on complete graphs to sidestep this situation. As it stands, your example is infeasible. Is this intended?

**Comment by Zenilos** [comment]
Yes it was just a sample of csv file. I can make a bigger file of a network and host it somewhere.
I will update you.
Or can you make a folder in you repo and I can put my file there and make a pull request for that?
